= Introduction to Cisco CLI

Cisco devices typically uses one of four proprietary network operating systems. This software provides communication between the
resources on the Cisco routers, switches, firewalls, WAPs, and more. This ensures seamless communication and provides a CLI for
administrators to manage, configure, update, and troubleshoot the device and network. Below is a list of the four types of software found on Cisco devices.

== Cisco OS Types
[cols="3, 4"]
|===
| OS | Description

| Cisco IOS
| This is the traditional OS that everyone should be familiar with. It is found on both routers and switches, typically older models.
  It uses a monolithic architecture, which means all the processes run in a single memory space. While being lightweight and easy to use,
  it boasts no process seperation and has limited scalabilty.

| Cisco IOS-XE
| This architecture is found on newer Cisco devices. It uses a Linux daemon and allow process seperation and multithreading. 
  Despite being slighty more resource intensive than the traditional IOS, IOS-XE provides better faiult tolerance and supports network automation features.

| Cisco IOS-XR
| This architecture is mainly used by service providers in carrier-grade equipment. This is different from the previous two OSes which are typically found in the enterprise.
  IOS-XR uses a microkernel architecture running on QNX or Linux. Programs are fully serperated ensuring high reliability and performance.
  IOS-XR is built for high-throughput traffic environments and supports advanced features such as segment routing.

| Cisco NX-OS
| This architecture is found in data centers typically on Cisco Nexus switches. Using a Linux-based architecture it is designed for low-latency and reliabilty.
  It supports features like programmability and virtualization support. Due to its specialized nature it focuses more on a fabric-based approach for data centers rather than a traditional enterprise WAN.

|===

:note-caption: pass:[&#128161;]
NOTE: This documentation will primarily reference Cisco IOS commands

== Cisco CLI Modes

Cisco seperates access to the CLI for security and configuration purposes. Below is a list of the three types of modes.

[cols="2, 3"]
|===

| User Exec mode
| This is the mode the router/switch boots into. Administrators can perform basics functions such as monitoring and troubleshooting from a read-only perspective.
  User Exec mode is protected by the `line console` password (if accessing via the console) or the `line vty` password (if accessing via SSH). 
  This mode is denoted by a `>` following the name of the device. Ex. Router> or Switch>.

| Privileged Exec mode
| This mode on a router/switch is only accessible from User Exec mode using the command `enable`. This mode provides full read access to system files such as the running and startup conifg.
  Privileged Exec mode is protected by the `enable password` or `enable secret` password. This mode is denoted by a `\#` following the name of the device. Ex. Router# or Switch#. 

| Global Configuration mode
| This modes on a router/switch is only accessible from Privileged Exec mode using the command `configure terminal`. This modes offers full read/write access to configuration files. 
  Global Configuration mode is indirectly protected by the password set for Privileged Exec mode. This mode is denoted by the `(config)\#` following the name of the device.
  Ex. Router(config)# or Switch(config)#. 

|===

== Saving configurations
When modifying configurations on Cisco devices it is always important to save your changes. *This is not done automatically!* You must manually save your changes in the command-line with
the following commands. From either *privileged exec mode* or *global configuration mode* you can do `copy running-config startup-config` (which is prefered) or `write memory`.


Cisco devices have two configuration files:

- The *startup-config* - which is stored in NVRAM and is loaded up when the device next boots.
- The *running-config* - which is stored in RAM and holds changes made during the current session.

:warning-caption: pass:[&#128680;]
WARNING: *Ensure that you save your changes using `copy running-config startup-config` or your changes will be discarded!!!*

== Basic Commands
[cols="1, 4"]
|===
| Command
| Description

| `enable`
| Allows user to enter into Privilege Exec mode

| `configure terminal`
| Allows user to enter into Global Configuration mode

| `exit`
| Move to a previously level in the configuration hierarchy

| `end`
| Returns to Privilege Exec mode from any configuration mode

| `show startup-config`
| Displays the startup configuration stored in NVRAM. This file loads on boot until it is modified

| `copy running-config startup-config`
| Copies changes made in the current session to NVRAM

| `copy startup-config running-config`
| Will revert changes to the startup configuration. This can be done when an unwanted change have been made

| `hostname`
| Used to rename the device's default name

| `interface <interface-name>` or `interface range <interface-names>`
| Used to access `config-if` mode and apply changes directly to an interface





