= IPv4 Addressing

An IP (Internet Protocol) address is a numerical identifier given to a device on a computer network. They are designed to provide local addressing as well
as serve as an identifier of the NIC (Network Interface Card). These addresses are built on the foundation of Internet Protocol, a communications
protocol designed for relaying datagrams across different networks. 

== What is an IPv4 Address?

An IPv4 address was the first speciifcation of the IP address. It is comprised of a 32-bit number that takes the format of dotted-decimal notation or `X.X.X.X`. For example an IPv4 address can look like `192.168.0.1`. Each segment or byte can contain a value of 0-255. The function of IP addresses is to identify the host on the network and to
provide its location. Being 32-bits in length this limits the number of IP address to 2^32 or 4,294,967,296 addresses. This is much to small for our modern Internet. Since IPv4 exhaustion in the 2010s we have been forced to use IPv6 addresses. However, movement towards IPv6 really began back in the early 2000s. IPv6 which we will discuss in another post offers 2^128 addresses.

== Classful Addressing

To understand how modern IPv4 networks operate we must first go back to 1981. This is when classful addressing was implemented. This classful method catergorized
IPv4 addresses into 5 distict classes; A, B, C, D, and E. The class is denoted by the high-order/most significant bits (left-most bits). Each class corresponds to a distinct ordering of bits and a specific purpose.

[cols="1, 1, 1, 1"]
|===
|Class
|Network Prefix Size
|Host Prefix Size
|Address Range

|A
|8
|32
|0.0.0.0 - 127.255.255.255

|B
|16
|16
|128.0.0.0 - 191.255.255.255

|C
|24
|8
|192.0.0.0 - 223.255.255.255

|D and E
| -
| -
| 224.0.0.0 - 255.255.255.255

|===

:note-caption: pass:[&#128161;]
NOTE: Class D and E are reserved for multicast and experimenetal addressing purposes

== CIDR

In modern networks we have moved away from classful addressing in favor of a more versatile addressing scheme, Classless Inter-Domain Routing (CIDR).
CIDR was designed to prevent wastage of IP addresses and reduce the size of global routing tables. CIDR is based on Variable-Length Subnet Masking (VLSM) in which
address boundaries can be placed on any bit-boundary. This means that network addresses can now have variable sized network addresses. This prevents the wastage of IP addresses because a network can now be subnetted into a smaller network.
Before RFC 1918 (we'll get to that in a minute) customers had to use publicly routable addresses for both internal and external devices. For example if an organization had 500 devices they couldn't use a class C address (256 address limit). They had to move to a class B network (65536 address limit) despite only have 500 devices. This is a severe waste.

In order to resolve this not only did CIDR help, but so did RFC 1918 and NAT. Just briefly as we'll touch on it at a later date. They both work codependently of each other. Network Address Translation (NAT) translates publicily facing IP address into private addresses or vice versa on an organizations router or between networks with varying address assignments. RFC 1918 defines the private IP address range. They addresses are non-routable and defined for internal use to reduce the need for public addresses on internal devices. They addresses are defined as the following:

[cols="1, 1, 1, 1"]
|===
|Address Range
|Network Prefix Size
|Host Prefix Size
|Number of Usuable Addresses

|10.0.0.0 - 10.255.255.255
|8
|24
|16,777,216

|172.16.0.0 - 172.31.255.255
|12
|20
|1,048,576

|192.168.0.0 - 192.168.255.255
|16
|16
|65,536

|===

== IP Addressing Commands




